# Generated by Django 5.0.2 on 2024-02-11 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroFormularios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro_data', models.DateTimeField(auto_now_add=True)),
                ('ult_atual_data', models.DateTimeField(auto_now=True)),
                ('log_n_edicoes', models.IntegerField(default=1)),
                ('formulario', models.CharField(max_length=140)),
                ('tabela', models.CharField(max_length=140)),
                ('descricao', models.TextField()),
                ('publico', models.CharField(choices=[('discente', 'Discente'), ('docente', 'Docente'), ('colaborador', 'Colaborador')], max_length=20)),
                ('del_status', models.BooleanField(default=False)),
                ('del_data', models.DateTimeField(blank=True, null=True)),
                ('del_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='contrato_deletado', to='usuarios.usuarios')),
                ('usuario_atualizacao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='contrato_edicao', to='usuarios.usuarios')),
                ('usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='contrato_registro', to='usuarios.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='FormAvaliacaoDisciplinas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeiro_registro', models.DateTimeField(auto_now_add=True)),
                ('ultimo_registro', models.DateTimeField(auto_now=True)),
                ('log_n_edicoes', models.IntegerField(default=1)),
                ('disciplina', models.CharField(choices=[('introducao_agronegocio', 'Introdução ao Agronegócio'), ('estudos_culturais', 'Estudos Culturais e Antropológicos')], max_length=140)),
                ('ano', models.PositiveIntegerField(default=2024)),
                ('semestre', models.PositiveIntegerField(default=1)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('p1_disciplina_objetivos_claros', models.PositiveIntegerField(blank=True, null=True)),
                ('p2_conteudo_disciplina', models.PositiveIntegerField(blank=True, null=True)),
                ('p3_bibliografia', models.PositiveIntegerField(blank=True, null=True)),
                ('p4_grau_dificuldade_disciplina', models.PositiveIntegerField(blank=True, null=True)),
                ('discente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='avaldisciplina_discente', to='usuarios.usuarios')),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='info_formulario', to='formularios.registroformularios')),
            ],
        ),
    ]
