# Generated by Django 5.0.2 on 2024-02-11 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('data_ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('tipo_usuario', models.CharField(choices=[('discente', 'Discente'), ('docente', 'Docente'), ('colaborador', 'Colaborador')], max_length=15)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('matricula', models.CharField(max_length=14, unique=True)),
                ('nome_completo', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('usuario_is_ativo', models.BooleanField(db_index=True, default=True)),
                ('del_status', models.BooleanField(default=False)),
                ('del_data', models.DateTimeField(blank=True, null=True)),
                ('del_cpf', models.CharField(blank=True, max_length=14, null=True)),
            ],
        ),
    ]
